apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: golangs.example.io
  labels:
    module: my-module
spec:
  group: example.io
  scope: Cluster
  names:
    plural: golangs
    singular: golang
    kind: Golang
  preserveUnknownFields: false
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: Go Compiler.
          required:
            - spec
          properties:
            spec:
              type: object
              description: Spec of Go Compiler.
              required:
                - version
              properties:
                version:
                  type: object
                  description: Golang version.
                  required:
                    - major
                    - minor
                    - patch
                  properties:
                    major:
                      type: integer
                      description: Major version of Golang.
                      default: 1
                      enum:
                        - 1
                    minor:
                      type: integer
                      description: Minor version of Golang.
                      minimum: 0
                      maximum: 24
                      default: 24
                    patch:
                      type: integer
                      description: Patch version of Golang.
                      default: 0
                      minimum: 0
                      maximum: 17
                modules:
                  type: array
                  description: A list of modules to install.
                  items:
                    type: object
                    description: A module to install.
                    required:
                      - name
                    properties:
                      name:
                        type: string
                        description: Name of the module.
                      version:
                        type: string
                        description: Version of the module.
                      source:
                        type: string
                        description: Source of the module.
                      extraArgs:
                        type: array
                        description: Extra arguments for pip install.
                        items:
                          type: string
