{{- if .Values.echoserver.registry }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registrysecret
  namespace: {{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "echoserver")) | nindent 2 }}
data:
  .dockerconfigjson: {{ .Values.echoserver.registry.dockercfg }}
{{- end }}
